name: stock_data_hub
description: "A new Flutter project."
publish_to: 'none'

# Application version
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_database:
  firebase_auth:
  shared_preferences: ^2.0.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


