// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUWZP90gx6IUhsHxRyATKe-XGsKXmSKI',
    appId: '1:428208779028:web:a62b11e970cf98228e1c01',
    messagingSenderId: '428208779028',
    projectId: 'inventorymanagementsyste-1b85a',
    authDomain: 'inventorymanagementsyste-1b85a.firebaseapp.com',
    storageBucket: 'inventorymanagementsyste-1b85a.firebasestorage.app',
    measurementId: 'G-2W39HFHG2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTJspz-P5CtbNeDWCnQig4PsGFgqEt7g',
    appId: '1:428208779028:android:d9657ace6d49e6798e1c01',
    messagingSenderId: '428208779028',
    projectId: 'inventorymanagementsyste-1b85a',
    storageBucket: 'inventorymanagementsyste-1b85a.firebasestorage.app',
  );
}